### ISSUE TITLE
Piksi Multi Carrier Board,  RS232 Port SMD component problem 

### ISSUE THREAD

**Issue by RaiBearG** [swift-nav/piksi_hardware#1]
I was out on the field trying to test the multi and realized that the RS232 cable wouldn't connect with one of the carrier boards. Though the Multi was working and had an RTK fix, and the TX light on the board was blinking continuously. I was able to open the console and everything. Soon realized that if I pinched the board just the right spot, the communication would happen. Turns out, one of the SMD components (most likely a resistor) popped off from the bottom. It was working fine last night, so it must have been my  handling at the field today that caused it. 

![untitled drawing 2](https://cloud.githubusercontent.com/assets/18545820/23188875/39927d40-f845-11e6-8027-a47a244271e2.png)

![untitled drawing 1](https://cloud.githubusercontent.com/assets/18545820/23188785/da72e908-f844-11e6-9c1b-791f2eca2064.png)

I am using the TTL uart port for now. Seems like that component was connected to the TI multiplexer. I am assuming, without it the signal always goes to the picoblade ttl connector.
Imma build a case to help prevent this from happening. Hopefully there will be ways to make this more robust. Field testing is usually very rough and hardcore. 

Rai

**Comment by silverjam** [comment]
Gonna close this issue @RaiBearG ;-)
